

tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: "on-partial"  # Enables CLI auto-prompting for incomplete commands
    before: |
      # Install AWS CLI globally
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      
      # Ensure AWS CLI is available
      aws --version  # Verify installation
      
      # Return to the root of the workspace
      cd $THEIA_WORKSPACE_ROOT